func main() int {
  error 1+2;
  return 0;
}
